### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [marcobra/QuickMultiAttributeEdit3#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by marcobra** [comment]
Paolo dimmi se esiste una funzionalità. che ti consenta di fare ciò che fa
questo plugin.

1 - richiamare tramite un tasto funzione andare in edit per modificare
velocemente il valore di un campo di uno o più elementi (selezionato o
selezionati)

2 - tenere in memoria l'ultimo valore e campo immesso in modo da editare
velocemente valori ed avere memoria del dato inserito

se esiste in qgis3 una funzionalità così comoda ed utile che sostituisce
questa utilità, me lo diresti per favore, così lo pubblico il dettaglio per
tutti gli utenti che hanno scaricato il plugin per la versione di qgis2

non dirmi che c'è il multiedit non è la stessa cosa per chi lavora in input
di dati sul campo

grazie
Marco Braida

Il dom 28 ott 2018 06:24 Paolo Cavallini <notifications@github.com> ha
scritto:

**Comment by pcav** [comment]
OK, you bought me. Probably good too add these notes to the About.
Thanks.

**Comment by marcobra** [comment]
Ciao,

marcobra marcobra (marcobra.ubuntu@gmail.com) ti ha invitato a modificare la cartella " temporanea " su Dropbox.

Vai alla cartella[1]

Buon divertimento.
Il team di Dropbox

[1]: https://www.dropbox.com/l/scl/AACRh6U7WcYmfSTF9GJbx3YppN8_1VqMrV8

**Comment by pcav** [comment]
?
