### ISSUE TITLE
Cancel button

### ISSUE THREAD

**Issue by trembpo** [marcobra/QuickMultiAttributeEdit3#4]
I'm using QGIS 3.4.15 and the cancel button does not cancel the operation. The operation is launched instead of being canceled. For now, the x button works.

![cancel](https://user-images.githubusercontent.com/61712237/75715933-432e9000-5c9c-11ea-9c26-91a34fa6c52c.png)

Thanks

**Comment by marcobra** [comment]
Thank to report... i think i have dress this issue
